### ISSUE TITLE
Üb/Trees: Beweisen dass der split bei den Bäumen so ist wie auf den Slides bei den Cat Predicors in der Grafik

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#1016]
Wo man nach den Frequenzen der Klasse 1 in A-D sortiert. 
Das wurde ja programmiert, sollte man als Studi mal per hand nachrechnen.

**Comment by pkopper** [comment]
möchtest du das als Übung?

**Comment by pkopper** [comment]
@berndbischl still wished?
--> moved to wish list
