### ISSUE TITLE
Axis label on feature importance plots 

### ISSUE THREAD

**Issue by christian-hobelsberger** [slds-lmu/lecture_i2ml#1052]
Slides: [slides-forests-featureimportance.pdf](https://github.com/slds-lmu/lecture_i2ml/blob/master/slides-pdf/slides-forests-featureimportance.pdf)
I believe the axis labels on the feature importance plots for Accuracy on slides 0 and 2 may be incorrect. To improve accuracy, the Gini should be reduced, which would mean the x-labels should be changed from **MeanDecreaseAccuracy** to **MeanIncreaseAccuracy**.
<img width="338" alt="image" src="https://user-images.githubusercontent.com/52548126/212474268-ff65967f-7dc2-44f0-b152-313c79ebfa15.png">

**Comment by ludwigbothmann** [comment]
Thx @christian-hobelsberger we will take care of this

**Comment by holgstr** [comment]
Hi @christian-hobelsberger thank you for pointing this out. Unfortunately, the plot is misleading. MeanDecreaseAccuracy is a measure computed based on permutations of OOB observations, so should be on slide 3/3. MeanDecreaseGini is a measure computed based on improvement in the split criterion, so should be on slide 2/3. Both plots ended up on the same slide as they are output of `randomForest::varImpPlot()`. The plot itself is correct, i.e., higher decrease in accuracy = higher feature importance. Here is the more detailed explanation from the randomForest documentation: _MeanDecreaseAccuracy is computed from permuting OOB data: For each tree, the prediction error on the out-of-bag portion of the data is recorded (error rate for classification, MSE for regression). Then the same is done after permuting each predictor variable. The difference between the two are then averaged over all trees, and normalized by the standard deviation of the differences. If the standard deviation of the differences is equal to 0 for a variable, the division is not done (but the average is almost always equal to 0 in that case)._ Thanks again, we will find a way to correct this on the slides!

**Comment by manuelhelmerichs** [comment]
wurde bereits umgesetzt
