### ISSUE TITLE
Small notation error on the ROC curve slides

### ISSUE THREAD

**Issue by christian-hobelsberger** [slds-lmu/lecture_i2ml#1059]
Slides: [slides-evaluation-roccurves.pdf](https://github.com/slds-lmu/lecture_i2ml/blob/master/slides-pdf/slides-evaluation-roccurves.pdf) [Slide 5/16]
If I'm not mistaken, one too many parentheses are closed in the left expression.

**Comment by ludwigbothmann** [comment]
Yes, indeed, thank you @christian-hobelsberger !
