### ISSUE TITLE
[fix] description of make in CONTRIBUTING.md

### ISSUE THREAD

**Issue by ludwigbothmann** [slds-lmu/lecture_i2ml#1166]
:bug: :bug: :bug:

:warning: *Please provide specific & actionable issue titles!*

## Chapter name
*Please also flag with corresponding label*

No chapter, https://github.com/slds-lmu/lecture_i2ml/blob/master/CONTRIBUTING.md

## Location 
*Please provide as much context as possible, slide numbers change easily*

https://github.com/slds-lmu/lecture_i2ml/blob/master/CONTRIBUTING.md#slides

## Description & proposed fix

The guide says to use `make clean` for deleting PDF files, but this does not work anymore, apparently this was changed to `make rmpdf`? If yes, please update the contributing.md, thanks @lisa-wm !

**Comment by lisa-wm** [comment]
I'm not quite sure tbh, for me this still works, and the `clean` target also still exists in the [Makefile](https://github.com/slds-lmu/lecture_i2ml/blob/master/slides/tex.mk). Could you please elaborate @ludwigbothmann?
On another note, I updated the guidelines regarding compilation (new margin handling) - sorry for the delay :) https://github.com/slds-lmu/lecture_i2ml/pull/1169

**Comment by ludwigbothmann** [comment]
now I see it as well, it is even more confusing :) in exercises it is `make rmpdf` in slides it is (as it was always) `make clean` => any idea why?

**Comment by lisa-wm** [comment]
can we close this one, then @ludwigbothmann?

**Comment by lisa-wm** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean makefiles & update contribution guidelines](https://trello.com/c/dJAcuFuk/334-clean-makefiles-update-contribution-guidelines)
