### ISSUE TITLE
[add] Term "hard label classifier"

### ISSUE THREAD

**Issue by ludwigbothmann** [slds-lmu/lecture_i2ml#1224]
:heavy_plus_sign: :heavy_plus_sign: :heavy_plus_sign:

:warning: *Please provide specific & actionable issue titles!*

## Description
We do not seem to mention the term "hard-label classifier" on the slides. We should do that. The h(x) is already there, so minor fix needed

**Comment by manuelhelmerichs** [comment]
now under basic definitions
