### ISSUE TITLE
[fix] naive bayes: variances

### ISSUE THREAD

**Issue by ludwigbothmann** [slds-lmu/lecture_i2ml#1225]
:bug: :bug: :bug:

## Chapter name
Supervised Classification - naive Bayes

## Location 
Definition of Naive Bayes

## Description & proposed fix
It is not entirely clear - notation-wise - that variances of the features given class may differ over classes (it is I guess clear that they may differ over features)

Fix: add subscript for classes

**Comment by manuelhelmerichs** [comment]
subscript is now there
