### ISSUE TITLE
[fix] QDA - covariance matrices

### ISSUE THREAD

**Issue by ludwigbothmann** [slds-lmu/lecture_i2ml#1226]
:bug: :bug: :bug:

## Chapter name
Supervised Classification - QDA

## Location 
Definition QDA

## Description & proposed fix
Some students think that LDA is not a special case of QDA but that LDA and QDA are mutually exclusive

Fix: Change wording to something like "in QDA, Sigma_k *may* vary"

**Comment by manuelhelmerichs** [comment]
should be clear now, "QDA is a generalization of LDA" in bold
