### ISSUE TITLE
dataset appendix

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#199]
wir wollen wir bei rcourses einen "dataset appendix", der die beispiel datensätze kurz vorstellt

**Comment by berndbischl** [comment]
es wäre schön wenn wir das sehr schnell dichtmachen könnten

**Comment by HeidiSeibold** [comment]
Has this been finished in RCourses? Can this be shared with us?

@berndbischl

**Comment by fabian-s** [comment]
see also https://github.com/compstat-lmu/lecture_i2ml/pull/240

**Comment by HeidiSeibold** [comment]
What is the status here?
