### ISSUE TITLE
ROC extra stuff

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#271]
i removed some stuff into a file
roc-extra-unused.Rnw

that is somwhat old, and outdated
but there is also some potentially good stuff in there

should be reviewed for a potential extra lecture material, maybe we also need separate issues for this

**Comment by HeidiSeibold** [comment]
This is a general discussion we should have. See #449

**Comment by ludwigbothmann** [comment]
we have a new chunk now
