### ISSUE TITLE
bernoulli loss introduction is too complicated

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#276]
i like what fabian did there, but at the end we still introduce the maxlik principle, and go from there to the neg log likelihood. 

thats essentially the way it is currently written down and not every step seems "intuitive"
(why do we from a product and so on)

my suggestion is this:
a) start with the brier score. thats L2 on probs. especially after the linmod / L2 everyone should understand that

b) than introduce logloss VISUALLY and eplain the concept of "this penalizes confidently wrong"  prediction. and  compare to Brier, visually and otherwise.

i think we also need to unify / make consistent my current chapter 3 about performance measures.
it is a bit redundant now. and we should check for consitency between the 2

**Comment by berndbischl** [comment]
e.g. i think i used the term "log loss"

**Comment by fabian-s** [comment]
brier score definitely needs to come up in classification chapter, is used in CART chapter but never defined before that.

**Comment by tpielok** [comment]
Can this be closed now? Bernoulli loss is only stated in the new slides, not introduced anymore.

**Comment by lisa-wm** [comment]
no longer a problem because eval chapter handles all losses and is before CART. suggestions from first comment BB are in place now. advanced risk min contains deep dive to all losses
