### ISSUE TITLE
most plots which are not ggplot2, should BECOME ggplot2

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#285]

**Comment by RifatMehreen** [comment]
**Lecture I2ML:**

**01-Intro:**
	-slides-knn.Rnw: In comparison between Euclidean and Manhattan Dist. only plot is used
	-slides-limo.Rnw: in baseplot function plot is used in line 282, in line 366
	-slides-notation.Rnw: only qplot is used

**02-Classification:**
	-nothing to change

**03-performance:**
	-slides-overfitting.Rnw: only plot was used
	-slides-resampling.Rnw: plot was used for class distribution
	-slides-train-test.Rnw: slide page-10 ggplot is not used for plotting  

**04-Trees:**
	-nothing to change

**05-tuning-nested:**
	-nothing to change
