### ISSUE TITLE
In logistic regression don't name the losses differently

### ISSUE THREAD

**Issue by schalkdaniel** [slds-lmu/lecture_i2ml#292]
logistic loss and bernoulli loss now only depends on the label with 0,1 or +1,-1
this is confusing, as the loss itself is completely the same and its all equivalent

we should not use different names here

**Comment by fabian-s** [comment]
people prob should still know both terms as they come up in the literature. 
agreed that we should  put more emphasis on them being equivalent.

**Comment by berndbischl** [comment]
just for reference: i actually typed the issue for daniel :)

> people prob should still know both terms as they come up in the literature.

100% agree. it just currently sounds its somehow "really different".
and its especially weird that we pretend that bernoulli can only be used for +1,-1

**Comment by berndbischl** [comment]
i also REALLY want to empasize this in cim2

http://arogozhnikov.github.io/2016/07/12/secret-of-ml.html

**Comment by fabian-s** [comment]
> http://arogozhnikov.github.io/2016/07/12/secret-of-ml.html

this is SUPER nice. we have to work this in.

**Comment by berndbischl** [comment]
gerne mündlich weiter bereden, tippen dazu ist nervig

**Comment by fabian-s** [comment]
also: check again if we can avoid having BOTH 0/1 and -1/1 codng for binary responses in i2ml to avoid this

**Comment by tpielok** [comment]
Can this be closed now? The codings have been removed in the new slides and it's now clear that both losses are the same.

**Comment by lisa-wm** [comment]
yes, we now make it clear that the names are used interchangeably. there is also a deep dive in advanced risk min
