### ISSUE TITLE
document & improve build procedure for online presence

### ISSUE THREAD

**Issue by fabian-s** [slds-lmu/lecture_i2ml#309]
we build&deploy the website by triggering pkgdown via travis on a push to master.

this does not guarantee that the links in "Content" point to the most recent/corrected versions of the slides or exercises. 
can/should we do this as well?

**Comment by fabian-s** [comment]
thought: 
if we package this as an "R package", maybe the different slide sets and exercise sheets should be rendered as/treated as  vignettes as well -- then the pkgdown site would automatically point to their latest versions? not sure how much cross-referencing of vignetttes pkgdown supports?

**Comment by fabian-s** [comment]
this 

https://slu-soc5650.github.io/

seem worthy of emulation --

they use R markdown, embed videos, etc all in bookdown, with rendering/publishing via travis , IIUC
 
the course itself has one repo per lecture, not sure how/why that works yet...

**Comment by fabian-s** [comment]
remaining open points from here:
https://github.com/compstat-lmu/lecture_i2ml/issues/385#issuecomment-553458162

**Comment by fabian-s** [comment]
closed in ee8d5f3. remaining open points are website-related, so moved to #385.

**Comment by fabian-s** [comment]
https://www.shinyproxy.io/

this seems to offer shiny hosting from your own network, so we could host the interactive parts from a docker container running on LRZ infrastructure?

**Comment by HeidiSeibold** [comment]
Cool other projects:

- https://datasciencebox.org/
- https://codefreezr.github.io/awesome-LearnRwithR/
