### ISSUE TITLE
Concept Map: Write up high-level  content summaries and how they relate to each other

### ISSUE THREAD

**Issue by fabian-s** [slds-lmu/lecture_i2ml#315]
- dependency graph of all 10-20 min chunks in this lecture
- explicit definitions of learning goals for each chapter / chunk

--> make this more modular, more easily extensible, improve didactic structure

(kind of like a header file for a C program.)  
(should ideally also include -- at some point -- mathematical / prob-theory / programming prerequisites for each chunk)

**Comment by HeidiSeibold** [comment]
Can we generate this automatically from the lines in slides:

```
%! Includes:
```
?

**Comment by fabian-s** [comment]
> Can we generate this automatically from the lines in slides:
> 
> ```
> %! Includes:
> ```
> 
> ?

... that would be the hope, yes.
