### ISSUE TITLE
cheatsheet for lecture

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#327]
would be nice to have a cheat sheet for the lecture, listing the most important definitions and also synonymous names for concepts

**Comment by RifatMehreen** [comment]
@berndbischl for the whole course you mean?

**Comment by berndbischl** [comment]
well, not exactly, at least not for now. 
but the lecture contains certain fundamental definitions, symbols, etc.
it would be nice to have them on 1-3 sheets of paper. 
at some point there can be sections for certain models and other stuff.
but right now i would aim for 2 pages of "fundamental"

you could really work in this now rifat, helps also with the restructuring

**Comment by berndbischl** [comment]
this is how we do this for mlr3, you could copy the template
https://github.com/mlr-org/mlr3cheatsheets

**Comment by berndbischl** [comment]
this is the "notation" slide, thats a starting point for content
https://github.com/compstat-lmu/lecture_i2ml/blob/devel/01-intro/slides-notation.Rnw

**Comment by berndbischl** [comment]
here are other peoples sheets, to get an impression
https://github.com/compstat-lmu/rcourses/issues/377

**Comment by RifatMehreen** [comment]
I will work on it then

**Comment by RifatMehreen** [comment]
The 1st version of chapter 1. Some edits might be needed. I will work on them.
[CheatSheet_i2ml_intro.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/3717382/CheatSheet_i2ml_intro.pdf)

**Comment by RifatMehreen** [comment]
@berndbischl This is what I did for the 1st day of the course. Let me know what you think about it. 
[CheatSheet_i2ml_1 (2).pdf](https://github.com/compstat-lmu/lecture_i2ml/files/3858343/CheatSheet_i2ml_1.2.pdf)

**Comment by RifatMehreen** [comment]
After adding \hat{y}
[CheatSheet_i2ml_1.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4040594/CheatSheet_i2ml_1.pdf)

**Comment by HeidiSeibold** [comment]
Which cheat sheets are still missing? Can I put them on the website (see #410)?

**Comment by RifatMehreen** [comment]
i am still not done with day 4 and 5. I was thinking of combining them both into one cheat sheet. Let me know if there is anything else that is needed to be included

**Comment by RifatMehreen** [comment]
These are all the cheatsheets which are completed: 

1. [CheatSheet_i2ml_intro.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4154799/CheatSheet_i2ml_intro.pdf)

2. [CheatSheet_i2ml_1.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4154802/CheatSheet_i2ml_1.pdf)

3. [CheatSheet_i2ml_2.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4154805/CheatSheet_i2ml_2.pdf)

4. [CheatSheet_i2ml_3.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4154812/CheatSheet_i2ml_3.pdf)

**Comment by HeidiSeibold** [comment]
Thanks @RifatMehreen for the update. Can you add a folder named `cheatsheets` in this repo and add the  sources (tex/Rnw/Rmd whatever you are using to create the CheatSheets)? 

Or did you have something different planned (e.g. with @fabian-s)?

**Comment by fabian-s** [comment]
No, we didn't plan anything.

@RifatMehreen : plz make a new branch based on branch devel or refactoring-w1920, 
create the folder like Heidi asked and then do a pull request.

**Comment by fabian-s** [comment]
Edit: 
These two : 

1. [CheatSheet_i2ml_intro.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4154799/CheatSheet_i2ml_intro.pdf)

2. [CheatSheet_i2ml_1.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4154802/CheatSheet_i2ml_1.pdf)

have a large amount of overlap --- I don't think we want that?

**Comment by RifatMehreen** [comment]
I uploaded both the previous and new file. 

2. [CheatSheet_i2ml_1.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4154802/CheatSheet_i2ml_1.pdf) this one is the final one

**Comment by RifatMehreen** [comment]
> No, we didn't plan anything.
> 
> @RifatMehreen : plz make a new branch based on branch devel or refactoring-w1920,
> create the folder like Heidi asked and then do a pull request.

@fabian-s  Okay I will do that.

**Comment by HeidiSeibold** [comment]
@RifatMehreen where can I find that branch? We should merge it.

**Comment by RifatMehreen** [comment]
@HeidiSeibold I have created a new branch named **cheatsheets** and also made a pull request

**Comment by HeidiSeibold** [comment]
So we have 3 cheat sheets so far?

1. Notation
2. Supervised Classification
3. Evaluation

Is that correct? Any plans to do more?

- Supervised Regression
- Trees
- Random Forests
- Tuning

**Comment by RifatMehreen** [comment]
I am working on CART right now. I have plans to do more.

**Comment by RifatMehreen** [comment]
@HeidiSeibold @berndbischl This one is for CART. Let me know if anything needs to be changed.
[CheatSheet_i2ml_4.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4420341/CheatSheet_i2ml_4.pdf)

**Comment by RifatMehreen** [comment]
@HeidiSeibold @berndbischl @fabian-s This cheatsheet is for Regression. Let me know the feedback.
[CheatSheet_i2ml_5.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4449790/CheatSheet_i2ml_5.pdf)

**Comment by ludwigbothmann** [comment]
outdated
