### ISSUE TITLE
remove classif tasks slides and pics from chap1-basics

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#332]
there are quite a few slides on classif tasks
what should stay in 01:
a VERY short defintion of classification. MAYBE thats needed for "abgrenzung"
but as short as possible. if nothing stays, also ok, then we introduce classif completely in 02

pics BB already moved to 02 (and must be deleted in 01):

../ml-basics-regression/figure_man/lie-detector-polygraph.jpg cp
../ml-basics-regression/figure_man/webmd.png

**Comment by ludwigbothmann** [comment]
outdated
