### ISSUE TITLE
it would be nice to have a SIMPLE model example for chap and / or chap2

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#345]
so we can explain the concepts with an example
this is hard because we dont want to foreshadow the LM (or some other concrete model) here,
and i currently dont have a better example

try to think about this a bit?
if not possible --> close

**Comment by HeidiSeibold** [comment]
Maybe too late for this year? But would be nice to have, I agree.

**Comment by ludwigbothmann** [comment]
outdated
