### ISSUE TITLE
write mini documentation for chunk structure

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#361]
in README_internal. 
https://github.com/compstat-lmu/lecture_i2ml/blame/devel/README_intern.md#L18 ff.
relating already to the new branch

must cover:
- makefiles
- input / output comments
- naming of files

but i think there is quite a few more points, i should check / think about this a bit
eg.
- headlines
- latexmath
- etc

**Comment by fabian-s** [comment]
see https://github.com/compstat-lmu/lecture_i2ml/blame/devel/README_intern.md#L18 ff.
we don't have a wiki, i don't think we need one.

**Comment by berndbischl** [comment]
yup, all ok.
