### ISSUE TITLE
integrate new material in to refactoring w1920 (clustering, boosting, etc)

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#362]
there is not much to do, but we need to
- copy the files, maybe rename a bit
- maybe somehwhat smaller chunks would be good
- use new makefiles

write a text on the webpages that explains the new  material which is not covered by videos and the "growing" process. i guess we need like an "extra stuff" webpage or so.

for the last point BB should talk to @fabian-s briefly

**Comment by berndbischl** [comment]
this must be finsihed around 25.9.19

**Comment by HeidiSeibold** [comment]
Well it seems like this did not work out. What do we do here?

Probably also related to #449 "What to do with ideas that don't fit in 3 ECTS course"
