### ISSUE TITLE
Create speaker notes (script) 

### ISSUE THREAD

**Issue by HeidiSeibold** [slds-lmu/lecture_i2ml#384]
I think it might be worthwhile to create speaker notes (which should turn into a script) while creating the slides.

This comes with several benefits:

1. There is a script and creating videos gets much easier
2. The slides can become more focused on what the learner should see (less what the speaker needs to remember). A general rule for slides should be: **As little text as possible**
3. The people who create the slides can document what they intend the speaker to say.
4. When printing the slides we can choose to print them with notes/script or without. This may help students for learning.

See e.g. https://tex.stackexchange.com/questions/395715/making-slides-also-handouts-with-notes for beamer notes.

**Comment by berndbischl** [comment]
hmm. this seems a lot of work. not sure if we can do this. 
i also only put stuff on slides, which the reader should see.

**Comment by berndbischl** [comment]
what i dislike are slides, which are incomprehensible, when you read them

**Comment by HeidiSeibold** [comment]
Currently when I watch the videos I have to decide: Do I want to (a) listen or (b) read the slides.

This is not "just" my opinion/observation. There is evidence that people cannot read sentences from slides _and_ listen to the speaker at the same time (if you want, I can look for references).

**Comment by berndbischl** [comment]
i dont need the refs, i know this

the point is:

a) its a matter of style, to a certain extend
b) its a very general issue
c) it might require rewriting everything

can you at least give an example to make this more concrete?
--> i dont even think this is dicussable in an issue. i guess we should move this to slack or discuss this in person

**Comment by HeidiSeibold** [comment]
> a) its a matter of style, to a certain extend

To a certain extend yes, but I think if we **focus** on good teaching, this is a major point we _could_ improve. 

> b) its a very general issue

Yes. Are general issues not allowed?

> c) it might require rewriting everything

We could first only implement it in slides we are redoing anyway or creating from scratch.

> can you at least give an example to make this more concrete?

Random slide from a video I am just looking at:

![image](https://user-images.githubusercontent.com/14146757/66397732-b75e5380-e9dc-11e9-9b64-b3bb33df82e2.png)
 https://github.com/compstat-lmu/lecture_i2ml/blob/master/slides-pdf/slides-intro-performance.pdf

Massive amounts of text. Mostly sentences. Main messages would only require:

---
Goals/types of performance estimation:

- Model performance evaluation
- Algorithm performance evaluation
- Model selection
- Learning curve estimation
---

Optimally I would show images/pictograms showing what I mean with each point.

> --> i dont even think this is dicussable in an issue. i guess we should move this to slack or discuss this in person

Happy to do so next week.

**Comment by HeidiSeibold** [comment]
> what i dislike are slides, which are incomprehensible, when you read them

This would not be the case if we use notes in beamer, I think. You _could_ always look at slides+notes.

**Comment by berndbischl** [comment]
wrt to your example: the reason the text is there as it *defines* the bullet points.

so removing them, would, in my view, make the slides less readable as information content now changes. 

i am all for reducing "noise", compressing information, and so on, as i get your point, in general. 
but exactly for this example, removing the text makes the slides worse, not better

**Comment by berndbischl** [comment]
Like I said: if we discuss this, which we can, it need to be in person, or in a call.
Agreeing with Fabians wallotext, mostly

**Comment by HeidiSeibold** [comment]
Thanks Fabian! Yes, lets discuss in person :)

**Comment by HeidiSeibold** [comment]
@fabian-s @berndbischl see https://github.com/compstat-lmu/lecture_i2ml/commit/d95ed69a405f3059e263941818f427f80510f98a for an example on how notes could work. 

Maybe helps with the discussion to see how I'd imagine it in practice.

**Comment by HeidiSeibold** [comment]
See #439
