### ISSUE TITLE
Cheat sheet - evaluation

### ISSUE THREAD

**Issue by HeidiSeibold** [slds-lmu/lecture_i2ml#429]
@RifatMehreen I will collect my ideas for the cheat sheet (see #327) for day 3 (evaluation) here. This is currently work in progress, but if you want / have time you can already get started. 

- [x] Rename metrics -> measures
- [x] Say which measure corresponds to which loss

**Comment by RifatMehreen** [comment]
Final cheatsheet for day 3:

[CheatSheet_i2ml_3.pdf](https://github.com/compstat-lmu/lecture_i2ml/files/4154312/CheatSheet_i2ml_3.pdf)

**Comment by ludwigbothmann** [comment]
outdated
