### ISSUE TITLE
What are "includes" slides from classification which evaluation measures depend on?

### ISSUE THREAD

**Issue by HeidiSeibold** [slds-lmu/lecture_i2ml#434]
Regression evaluation measures depend on
```
%! includes: regression-losses evaluation-intro
```

For classification I currently have:

https://github.com/compstat-lmu/lecture_i2ml/blob/39165094b3947ad95efd5d355fc954194b46533d/slides/evaluation/slides-evaluation-measures-classification.Rnw#L8

will there be slides `classification-losses`?

**Comment by HeidiSeibold** [comment]
@berndbischl any updates on this?

**Comment by lisa-wm** [comment]
no longer relevant
