### ISSUE TITLE
Use same color scheme (or just same plot) for log-loss in supervised-classification + evaluation-measures-classification

### ISSUE THREAD

**Issue by HeidiSeibold** [slds-lmu/lecture_i2ml#444]
Currently we have the same plot twice and colors and axis labels differ.

**Comment by HeidiSeibold** [comment]
Is this the case now @berndbischl or should we do it next year?

**Comment by ludwigbothmann** [comment]
Still inconsistent

**Comment by lisa-wm** [comment]
to do: use same plot, create as best of both worlds
use axis labels as in classification (chunk logreg) but add right/wrong annotation from eval (measures classification)

**Comment by berndbischl** [comment]
we should really have a library function here for these loss plots

**Comment by manuelhelmerichs** [comment]
will now use the same plot (https://github.com/slds-lmu/lecture_i2ml/pull/1269)
