### ISSUE TITLE
What to do with ideas that don't fit in a 3ECTS course?

### ISSUE THREAD

**Issue by HeidiSeibold** [slds-lmu/lecture_i2ml#449]
We often have ideas that would go well with the course but don't fit in *our* course in Munich (3 ECTS).

Examples:

#266 multiclass ROC
#267 calibration + discrimination 
#269 More detailed ROC
#270 ROC convex hull

What to do about them?

- Just nothing?
- Add as modules that can be used in other courses (taught somewhere else)?

This is also relevant for contributors in the future? Do we want to allow additional modules? What do you think @berndbischl @fabian-s

**Comment by HeidiSeibold** [comment]
Related to #448 
What to do with material we don't want to use anymore but may be useful in the future / for other lectures?

**Comment by fabian-s** [comment]
> Related to #448
> What to do with material we don't want to use anymore but may be useful in the future / for other lectures?

we have an attic folder for that stuff?
