### ISSUE TITLE
naive bayes: simple compuation / example

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#477]
we should showcase a simple example on data that demonstrages how we compute the model on data

**Comment by berndbischl** [comment]
https://monkeylearn.com/blog/practical-explanation-naive-bayes-classifier/

**Comment by ludwigbothmann** [comment]
We have a rather thorough exercise on this: ex_classification_2.pdf question 1

**Comment by manuelhelmerichs** [comment]
we have added a simple demonstration (as figure), is also explained in the new vids
