### ISSUE TITLE
Rename R figure files & plots

### ISSUE THREAD

**Issue by lisa-wm** [slds-lmu/lecture_i2ml#536]
Currently, R files producing figures and the resulting plots are named in an inconcise manner.
Mostly, they just carry the name of the chunk and a consecutive number.
Since many files produce multiple figures, there is no way of unambiguously connecting a plot to an R file just by name.
Also, chunking is not gonna remain the same forever.

* All R files and plots should be renamed with meaningful names
* A sensible naming convention could be:
  * R files: chaptername_meaningfulname.R --> e.g., evaluation_overfitting_rf.R
  * Figure files accordingly, with an additional consecutive number if multiple plots are produced --> e.g., evaluation_overfitting_rf.PDF, _or_ evaluation_overfitting_rf_1.PDF and evaluation_overfitting_rf_2.PDF
* Tex files must be adapted to the new names then

**Comment by ludwigbothmann** [comment]
@lisa-wm I would say this can be closed, unless you disagree?

**Comment by lisa-wm** [comment]
yes, done 👍🏻
