### ISSUE TITLE
[exercise] Iterate exercise sheets

### ISSUE THREAD

**Issue by ludwigbothmann** [slds-lmu/lecture_i2ml#562]
I would like to have a specific sprint just for the exercise material. Currently, the level of the lecture is much higher than that of the exercises. Or perhaps spread it out over the summer term 2021 in preparation of 21/22?

- Exercises should accompany lecture material better, now that we switched from block course to weekly format
- Exercises should support the learning goals of the lecture OR have their own learning goals. In every case: State the learning goals on the sheet (at least in the source - if not in the rendered version as well) so that we are sure why THIS exercise is useful
- Exercises could have a title, such as "Exercise 2: k-NN for classification", this helps future teachers to see quickly what the sheet is about, and most of all it helps students to orientate
- Folder structure is not optimal: single exercises should be in one large folder and exercise sheets should pull from there
- Organizationally: Do we stick to the plan that students should not prepare exercises but do them in groups in the live session? In winter 20/21 it turned out that q+a is too long for having group exercises afterwards. Perhaps switch to: Students prepare exercises in groups in the week before the live session and then present their solutions in the live sessions.

**Comment by ludwig-max** [comment]
- ROC question: Infer predicted probs from a given ROC curve (with given class sizes) => Exact values are not unique, but the order is.
- Part 2: Is it possible to derive 2 solutions that are really quite different? Showing that ROC doesn't tell the whole story.
