### ISSUE TITLE
[trees] source figure

### ISSUE THREAD

**Issue by ludwigbothmann** [slds-lmu/lecture_i2ml#574]
trees/figure_man/labelling_of_tree.png has no source - are we sure we may use this?

**Comment by ludwig-max** [comment]
Perhaps you can find the source? Or reproduce it easily? If this is a lot of work then we should talk.

**Comment by carobec** [comment]
I already did resolve this in the branch tree-redo.

**Comment by carobec** [comment]
@ludwig-max Can we close it? I reproduced it :)
