### ISSUE TITLE
[trees] figure regression

### ISSUE THREAD

**Issue by ludwigbothmann** [slds-lmu/lecture_i2ml#575]
this figure in cart-intro.pdf seems wrong: https://docs.google.com/presentation/d/1Pns5UJyc-Aqyk9d-CLekA46BC7UJ_e0uSdErat47opM/edit#slide=id.p

In interval 1 and 3 this can not be the mean. Where is the code that produced these estimates?

**Comment by ludwig-max** [comment]
cart_dis_2.pdf same

**Comment by ludwig-max** [comment]
Please compute the correct values and change the slides.

**Comment by pkopper** [comment]
more generally all images in this chapter look awful
