### ISSUE TITLE
Missing reference to the lecture

### ISSUE THREAD

**Issue by SebGGruber** [slds-lmu/lecture_i2ml#584]
Hey, I am trying to reference the lecture in my master thesis, but unfortunately the "Reference" page (https://compstat-lmu.github.io/lecture_i2ml/reference/index.html) is empty.
I guessed your desired format to look like this:

@misc{i2ml,
  title   = "Introduction to Machine Learning (I2ML)",
  author  = "B. Bischl and F. Scheipl and H. Seibold and L. Bothmann and D. Schalk and C. Molnar and T. Pielok",
  journal = {https://github.com/compstat-lmu/lecture_i2ml},
  year    = "2020",
  url     = {https://introduction-to-machine-learning.netlify.app}
}

If you prefer a different one, please tell me.

**Comment by pkopper** [comment]
Need to update authors

**Comment by manuelhelmerichs** [comment]
should be updated:

@misc{bischl22i2ml,
  author = {Bischl, Bernd and Bothmann, Ludwig and Scheipl, Fabian and Pielok, Tobias and Wimmer, Lisa and Li, Yawei and Kolb, Chris and Schalk, Daniel and Seibold, Heidi and Molnar, Christoph and Richter, Jakob},
  title = {{Introduction to Machine Learning (I2ML)}},
  howpublished = "\url{https://slds-lmu.github.io/i2ml/}",
  year = {2022},
  note = "[Online; accessed yyyy-mm-dd]"
}
