### ISSUE TITLE
[forests] figure source

### ISSUE THREAD

**Issue by ludwigbothmann** [slds-lmu/lecture_i2ml#588]
Source for figure_man/rf_majvot_averaging.png is missing.

**Comment by ludwig-max** [comment]
@lisa-wm @carobec Any idea where this could be from?

**Comment by carobec** [comment]
@ludwig-max I think it was added here from some "course"? But I am not sure... Should I recreate this with google slides?

I think this is the corresponding commit:
https://github.com/compstat-lmu/lecture_i2ml/commit/f69085a4d61e3aaa26b16926a0b97efd3d60b1b5

**Comment by ludwig-max** [comment]
Yes, that would be great @carobec thanks!

**Comment by lisa-wm** [comment]
we now only use home-made figures
