### ISSUE TITLE
[resampling] new results on CV error -- check content & possibly revise 

### ISSUE THREAD

**Issue by fabian-s** [slds-lmu/lecture_i2ml#613]
This paper 

https://statweb.stanford.edu/~tibs/ftp/NCV.pdf 

introduces some clarifying concepts and has some interesting results re. the accuracy of generalization error estimates.
![image](https://user-images.githubusercontent.com/998541/113269862-2cac9b00-92d9-11eb-9f02-cd36daad2e7d.png)

![image](https://user-images.githubusercontent.com/998541/113269538-d93a4d00-92d8-11eb-8406-0898366eabec.png)

(much in here possibly too subtle for these intro slides -- should still check that slides & voice-over don't simplify these issues too much. but feel free to close if irrelevant for an intro course)

**Comment by berndbischl** [comment]
we are adding videos and material from PM anyway to this page / repo AND are currently working on eval @tpielok 

so this is highly appreciated

**Comment by lisa-wm** [comment]
noted for future improvements
