### ISSUE TITLE
Collect learning goals for SL part

### ISSUE THREAD

**Issue by lisa-wm** [slds-lmu/lecture_i2ml#665]
create document listing all chapter-wise learning goals in analogy to [I2ML collection](https://docs.google.com/document/d/1fP_1c5k0u3LUoVPTo3jFoBGOOIFC4jQhkhYQI3Dpuwk/edit#heading=h.v8olhkbfam0h)

**Comment by holgstr** [comment]
@ludwig-max Learning Goals are updated in the Doc, however, from Chapter 19.1 onwards learning goals are missing in the slides.
