### ISSUE TITLE
set up resampling cheatsheet

### ISSUE THREAD

**Issue by lisa-wm** [slds-lmu/lecture_i2ml#705]
idea: build look-up with most important properties of resampling strategies at a glance (appropriate with few data, bias/var, ...)
kxp CV, pxk CV, k CV, holdout, BS, subsampling, LOO, LOOO, stratification, ...

**Comment by ludwigbothmann** [comment]
Add some sentences to the cheatsheet on tuning

**Comment by berndbischl** [comment]
we have the sheet
