### ISSUE TITLE
Update slides_i2ml.pdf

### ISSUE THREAD

**Issue by fxedel** [slds-lmu/lecture_i2ml#719]
Hey there,

The PDF containing all slides for the I2ML course, slides_i2ml.pdf, has not been updated for two months, but the slides for some chapters have been updated a few days ago.

As a student, its much easier working with a single large PDF than with hundreds of small PDFs.

So, could you please update or regenerate the whole slides_i2ml.pdf file?

**Comment by ludwig-max** [comment]
Hello @fxedel , yes, I can (and will) do this. However, you can also do it yourself by just compiling [this tex file](https://github.com/slds-lmu/lecture_i2ml/blob/master/slides-pdf/slides_i2ml.tex).

**Comment by ludwig-max** [comment]
done

**Comment by fxedel** [comment]
Thanks!
