### ISSUE TITLE
Wrong Variable in Laplace Distribution Chp 10.11, PDF page 1/6

### ISSUE THREAD

**Issue by davidruegamer** [slds-lmu/lecture_i2ml#838]
[Chp 10.11, PDF page 1/6](https://moodle.lmu.de/mod/forum/discuss.php?d=140808)
> \epsilon follows a Laplace distribution which has the density 
Why is there an x in the density function? \epsilon should make more sense.  Because this is the density of \epsilon.

**Comment by pkopper** [comment]
done
