### ISSUE TITLE
Simulation for bias-variance-decomposition

### ISSUE THREAD

**Issue by dandls** [slds-lmu/lecture_i2ml#853]
Simulation that in case of extreme variance of  trees (extremely randomized forests), 
fit gets at some point worse.

**Comment by pkopper** [comment]
maybe for SL not I2ML as students do not really (mathematically) work with the BV decomposition yet

**Comment by berndbischl** [comment]
this is a RF issue

**Comment by berndbischl** [comment]
for tress we will show the instability of the trees

**Comment by berndbischl** [comment]
not exactly sure whether this is actionable...

**Comment by berndbischl** [comment]
i think we are currently fine
