### ISSUE TITLE
Stop makefile via exception if R package is not installed

### ISSUE THREAD

**Issue by davidruegamer** [slds-lmu/lecture_i2ml#864]
When running the makefiles via `make -f Makefile` the process throws an error if required R packages loaded within the Rnw files are not installed.

**Comment by ludwigbothmann** [comment]
> this is obsolety if we put code into external files?

Yes, but in the exercises we still have some .Rnw files. However, Son created a nice script to make sure you have all the packages you need: https://github.com/slds-lmu/lecture_i2ml/blob/master/scripts/libraries_installer.R
