### ISSUE TITLE
Platt Scaling Multiclass: Why is it used? More explanations. 

### ISSUE THREAD

**Issue by juliambr** [slds-lmu/lecture_i2ml#872]
I think we should add some more detail here. 

Question asked by a student: 

> Each binary classifier can be transformed into posterior probabilities by using for example Platt’s method. The obtained probabilities must afterwards be normalized so that they sum up to 1.
> Ginge an dieser Stelle auch einfach Softmax? Mir ist nicht ganz klar, wo der Vorteil von Platt's scaling bzw. der zusätzlichen logistischen Regression liegt. Insbesondere weil Softmax in dem Kapitel eingeführt wird.

My answer: 

> Allgemein: 
> Platt Scaling (oder auch Platt Kalibration) wird üblicherweise dann verwendet, wenn ein Classifier per se keine oder schlecht kalibrierte Wahrscheinlichkeiten ausgibt (für die Definition von Kalibrierung s. Kapitel 14). Ursprünglich wurde das für die SVM entwickelt, da die Scores nur eine geometrische Interpretation besitzen (nämlich die Interpretation als Abstände zur Decision Boundary). 
> Während die Softmax-Funktion Werte lediglich auf das Intervall [0, 1] skaliert, wird durch Platt Scaling tatsächlich eine Klassenwahrscheinlichkeit geschätzt. 
> 
> Zurück zu One-vs-Rest: 
> Im Allgemeinen kann man nicht davon ausgehen, dass die ausgegebenen Scores direkt etwas mit Klassenwahrscheinlichkeiten zu tun haben. Zum einen geben die einzelnen Classifier nicht unbedingt Wahrscheinlichkeiten aus (z.B. wenn wir g verschiedene SVMs trainieren). Zum anderen kann es sein, dass das finale Multi-Class Modell nicht gut kalibriert ist (selbst wenn wir für die g binären Subprobleme Classifier benutzen, die „echte“ Wahrscheinlichkeiten ausgeben).
> Daher verweisen wir in diesem Szenario auf Platt Scaling / Multinomial Logistic Regression (was ebenfalls für Kalibrierung sorgt).

**Comment by lisa-wm** [comment]
calibration is handled in advanced ML (also some material in the attic)
