### ISSUE TITLE
we need to SLOWLY show what happens if you use a RBF kernel with the dec boundary and model

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#874]
what we need to show is that f is a (sparse) sum of gaussians, which are mixed and smooth each other out.

show with a formula but ALSO with pics / anim

**Comment by pkopper** [comment]
@berndbischl isn't this achieved by slides 2/3 (WEIGHTED MIXTURE OF GAUSSIANS) of slides-nonlinsvm-kernel-rbf.pdf

**Comment by berndbischl** [comment]
yes
