### ISSUE TITLE
Dataset Example / Illustration for Boosting 

### ISSUE THREAD

**Issue by giuseppec** [slds-lmu/lecture_i2ml#876]
The existing two boosting illustrations are already pretty cool.
Maybe a concrete data example as presented here https://youtu.be/3CC4N4z3GJc would also help to better understand the algorithm and the inner workings of gradient boosting trees. 
The lecture slides don't have to be as detailed as in the video but a similar, less detailed illustration would be great.
I really enjoyed watching the video.

**Comment by lisa-wm** [comment]
done
