### ISSUE TITLE
SVM: Review Notes

### ISSUE THREAD

**Issue by juliambr** [slds-lmu/lecture_i2ml#904]
- [ ]  p4: das bsp ist nicht total überzeugend, weil man gar nicht 3 features braucht, sondern nur 1? wir gehen also gar nicht notwendigerweise in einen höherdim raum?

- [ ]  6-7: wir sollten schreiben a) warum monomials denn vielleicht interessant sind? b) warum sie besonders interessant für die MNIST daten sind

- [ ]  p.11: entweder hier oder später sollten wir das auch wirklich mal mit einer SVM klassifiezieren mit einem polykernel um zu zeigen dass das auch wirklich geht

- [ ]  folie 107 etwas viel, aufteilen. ein kernel / prinzip pro folie. und wir MÜSSEN das mehr schreiben was die bedeuten und mehr visualisieren für einen satz könnten wir auch mal einen beweis zeigen. oder immer "proof is exercise " sagen

p44: ein bsp wäre toll wo man sieht dass die fehlerrate dann sehr hoch ist... (wenn die kernel width falsch gewählt wird) 
in 2d wäre ok mit plotLearnerPred leider hat man dieses bsp nur FAST auf folien 19 und 20 bereits. hohes signma: ja, aber zu kleines nein, weil die daten halt einen linear classifier nahelegen, dann sind super kleine sigma sehr gut..... wenn man das datenbsp leicht ändert würde es wohl gehen

**Comment by pkopper** [comment]
I think as slides have drastically changed most comments are obsolete now or not identifiable on slides.
