### ISSUE TITLE
Boosting: Better formalization of the exponential loss in boosting

### ISSUE THREAD

**Issue by schalkdaniel** [slds-lmu/lecture_i2ml#910]
We should add the loss L(...) = ... and with that the empirical risk R_emp = sum L(..) not just a formula with exponential loss is used here

**Comment by ludwigbothmann** [comment]
This is now commented out in slides-boosting-gbm-with-tress-2.tex see also https://github.com/slds-lmu/lecture_cim2/pull/678/files
