### ISSUE TITLE
precision-recall curves vs. roc für imbalacy

### ISSUE THREAD

**Issue by giuseppec** [slds-lmu/lecture_i2ml#917]
Für imbalanced classes sind hier sehr gute beispiele drin wo ROC kaputt geht:
- Nette Discussion dazu: https://stats.stackexchange.com/questions/7207/roc-vs-precision-and-recall-curves
- Super paper dazu > 2000 citations https://www.biostat.wisc.edu/~page/rocpr.pdf

Blogposts mit paar illustrativen Beispielen:
- https://towardsdatascience.com/what-metrics-should-we-use-on-imbalanced-data-set-precision-recall-roc-e2e79252aeba
- https://machinelearningmastery.com/roc-curves-and-precision-recall-curves-for-classification-in-python/

**Comment by ludwigbothmann** [comment]
Still valid imo

**Comment by berndbischl** [comment]
we have a dedicated chunk and will store the links from the OP
