### ISSUE TITLE
Advanced Trees & Forests: Model-Based Trees

### ISSUE THREAD

**Issue by juliambr** [slds-lmu/lecture_i2ml#927]
- [x] approx. 2 Slides: Motivation for model-based trees (https://medium.com/convoy-tech/the-best-of-both-worlds-linear-model-trees-7c9ce139767d, https://towardsdatascience.com/introduction-to-model-trees-6e396259379a)
- [x]  approx. 3 slides: Explain linear model trees formally & show examples  
- [x]  approx. 3 slides: Explain logistic model trees formally & show examples (this is the paper: https://link.springer.com/content/pdf/10.1007/s10994-005-0466-3.pdf )

**Comment by lisa-wm** [comment]
noted für future improvements. close issue because not relevant for current material.
