### ISSUE TITLE
SVMs: restructure this chapter

### ISSUE THREAD

**Issue by fabian-s** [slds-lmu/lecture_i2ml#947]
this contains multitudes. people get overwhelmed & lose track.

- [x] split off RKHS / kernel part into its own "kernels" lecture (and trim all unnecessary RKHS theory, eg the stuff about spans etc)
- [x] basic constrained optimization stuff now part of CIM1 (?), can be removed
- [x] primal-dual stuff needs to be part of a pure "optimization" lecture or should get more room here: for most people, first time they see this, so needs better explanation and examples.

**Comment by pkopper** [comment]
@berndbischl GPs werden aus der VL genommen, daher close ich das issue hier; die anderen Punkte wurden abgearbeitet
