### ISSUE TITLE
Mini bug

### ISSUE THREAD

**Issue by giuseppec** [slds-lmu/lecture_i2ml#972]
Wirklich nur mini Sachen: 

- Slide 2 ist die distance between point and plane immer positiv wegen dem betrag, in der nächsten Slide (zweiter Stichpunkt) kann die Distanz auch negativ sein (da y ja entweder -1 oder +1 sein kann). Sollten man vllt. vereinheitlichen.

- In Slide 5 kam die Frage auf warum man ||theta|| = 1/gamma setzt. Ich hab das so erklärt, dass man damit implizit die margin (und damit die Distanz zw. Support Vektoren und Hyperebene) auf den Wert 1 festlegt, d.h. die Nebenbedingung `y * (<theta*x> + theta_0 >= 1` kann für die Anderen Beobachtungen als relative Distanz zur den Support Vektoren interpretiert werden. Könnte man ggf. mit einem Satz erweitern.

- Slide 7, letzter Satz haben wir ein beta stehen. Ist doof, wenn wir später beta als lagrange multiplikator für die equality constraints einführen?

**Comment by pkopper** [comment]
alle ursprünglichen Kommentare scheinen resolved.
