### ISSUE TITLE
Varsel & Tuning 

### ISSUE THREAD

**Issue by MariaErdmann** [slds-lmu/lecture_i2ml#987]
Ín der Varsel-Vorlesung wird eine objective function eingeführt (Folie 21).
Eine solche objective function wird auch im Kapitel Tuning drankommen. Hier sollten wir uns bzgl der Notation überlegen, ob wir g(b) für diese Funktion so lassen wollen (g ist ja Anzahl der Klassen und b der Baselearner).

**Comment by ludwigbothmann** [comment]
outdated
