### ISSUE TITLE
rf: mtry besser diskutieren

### ISSUE THREAD

**Issue by berndbischl** [slds-lmu/lecture_i2ml#999]
ein mini extra section einbauen zum effekt von mtry.
das steht im hastie gut. hier gibt es auch ein simulationsbsp zum effekt von mtry

**Comment by lisa-wm** [comment]
https://hastie.su.domains/ElemStatLearn/printings/ESLII_print12_toc.pdf
chapter 15.4.1, Ex 15.6

**Comment by berndbischl** [comment]
i think we did that pretty well now
